#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

mount /dev/sdb1 /home -t ext4 || mount /dev/sdc1 /home -t ext4 || echo "No mountable home folder found"
swapon /dev/sdb2 || swapon /dev/sdc2 || echo "No mountable swap partition"